GET http://localhost:8080/admin
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImFkZHJlc3MiOiJuZXdJZEBuYXZlLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MTMyNTcyMjMsImV4cCI6MTcxMzI2MDgyM30.cYs88dD4oU8X3EjphtHaH8HFMdKTAPEN4Y_1aOps6F0