GET http://localhost:8080/admin
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImFkZHJlc3MiOiJuZXdJZEBuYXZlLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MTMyNTYwMjMsImV4cCI6MTcxMzI1OTYyM30.i2z5bmQkf2wotZedwFtbmCGrdpe4Psy5GwjV6HXZ5oM