GET http://localhost:8080/mypage
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImFkZHJlc3MiOiJuZXdJZEBuYXZlLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MTMzMzgwODQsImV4cCI6MTcxMzM0MTY4NH0.ZtmPMT459Eo0E_aTDDAAQudDl9cMQsKF_qdr5W3Ntak