GET http://localhost:8080/mypage
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImFkZHJlc3MiOiJuZXdJZEBuYXZlLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MTM1OTg1NzUsImV4cCI6MTcxMzYwMjE3NX0.qDniBcZUsacAHUv_4i-l96JK2zS_lFwNt7NSjzSJnR8