POST localhost:8080/reissue
Set-Cookie: refresh=eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InJlZnJlc2giLCJhZGRyZXNzIjoibmV3SWRAbmF2ZS5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzExODA0ODc0LCJleHAiOjE3MTE4OTEyNzR9.IuNTtA69Qv4uoo3Ld-4d7b6JkkqpBnQCY39SL6935jA