POST localhost:8080/reissue
Set-Cookie: refresh=eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6InJlZnJlc2giLCJhZGRyZXNzIjoibmV3SWRAbmF2ZS5jb20iLCJyb2xlIjoiUk9MRV9VU0VSIiwiaWF0IjoxNzE1MDAwOTEwLCJleHAiOjE3MTUwODczMTB9.d7r38YTde2nm4i6Eho85bhqQC-btr-03WDbGsygpS2Y