GET http://localhost:8080/test
access: eyJhbGciOiJIUzI1NiJ9.eyJjYXRlZ29yeSI6ImFjY2VzcyIsImFkZHJlc3MiOiJuZXdJZEBuYXZlLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MTM1OTk3MzcsImV4cCI6MTcxMzYwMzMzN30.326SDlLgLZdnee9Vqj1BMivUGfVNVbCXYvOG4yLznv0